sudo: required
language: c
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
install:
- nvm install 8
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- yarn
script: true
stages:
  - name: prescript
    if: branch IN (ci)
  - name: lint
    if: branch IN (master, ci, testci, develop) OR type == pull_request OR tag =~ /^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/
  - name: unittest
    if: branch IN (master) OR type IN (pull_request)
  - name: unittestandcoverage
    if: branch IN (ci, testci)
  - name: test
    if: branch IN (ci, testci, master) OR type IN (pull_request)
  - name: build
    if: tag =~ /^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/
jobs:
  include:
    - stage: prescript
      before_script:
      - ./scripts/ci_merge_script.sh
#     merge script may update dependencies
      script:
      - yarn
      os: osx
      - os: linux
    - stage: lint
      script:
      - yarn run lint
      os: osx
      - os: linux
    - stage: unittest
      script:
      - yarn run clean
      - yarn run unit
      os: osx
      - os: linux
    - stage: unittestandcoverage
#      only allow failures when not in a critical branch (ie: master, tag)
      allow_failures:
      - os: linux
      os: osx
      script:
      - yarn run clean
      - yarn run unit
      - yarn run unit:coverage
    - os: linux
      script:
      - yarn run clean
      - ./scripts/travis_headless_linux_unit_tests_script.sh
    - stage: test
      script: ./scripts/travis_headless_e2e_tests.sh test/features/backlog
      os: osx
    - os: linux
    - script: ./scripts/travis_headless_e2e_tests.sh test/features/data_curator
      os: osx
    - os: linux
    - script: ./scripts/travis_headless_e2e_tests.sh test/features/edit
      os: osx
    - os: linux
    - script: ./scripts/travis_headless_e2e_tests.sh test/features/file
      os: osx
    - os: linux
    - script: ./scripts/travis_headless_e2e_tests.sh test/features/find
      os: osx
    - os: linux
    - script: ./scripts/travis_headless_e2e_tests.sh test/features/help
      os: osx
    - os: linux
    - script: ./scripts/travis_headless_e2e_tests.sh test/features/other
      os: osx
    - os: linux
    - script: ./scripts/travis_headless_e2e_tests.sh test/features/support
      os: osx
    - os: linux
    - script: ./scripts/travis_headless_e2e_tests.sh test/features/tools
      os: osx
    - os: linux
    - script: ./scripts/travis_headless_e2e_tests.sh test/features/window
      os: osx
    - os: linux
    - stage: build
      os: osx
    - os: linux
      script:
      - yarn run clean
      - yarn run release:predraft
env:
  global:
    secure: F+Bn6BrNKTTybkEs4UwCl7961z7ura2zBeuw+tS/vXqswb//x9DEhEr5IJ53VyC+H2R3Wj8yJ121514FiJwNg4hUpUQ98DHyczbMLXrg+wjQI2ZYvhiAonR5LzDGNd/XLhSDezQK556+guq67SnGPP3iqnfjyu8XJ2IaynLukvLSazZTCliuqpEpwaCn99+xhaHLcGRF/Dh2Gg5+HVfQnC4S6eiYGo5Dm9RDG0hntxYHUOAxQYmnvXxf7uLNc0sfFSoVd1BZytZCVFLceY5DM0tOO8kRyMQk+LJqneAdhp9Z8pUMcTMDeJtNegqqSaBra8UAkrGv1tUrBYUQnq4fkbH0tees6mJNFkqNlOW67pj8zghYSAKwNXiazFmH/lYE2sleBKGflznLZPDD5XXLlQ/aKXF+3wAx0wMtiGkFBbGP+GoBg10+7RgKw0A+mpLaJAVwUYGGJSEfH3A0U0OEt7XRdk/sD4nFKLzL3SAx3QC57FdGu4VWdJJT9t54oX+NzM3QmBH3dNxmge4XFLR1iwN72yheB2HyGu5zafKdOfbvCz2fP1ddECm2KWu8I7NNuBIwoBUm3tVm60b3gTpblAO3RcIrLg3k+ACTSvxJuzqSIE2/YnXGnjfVPW/NaCcyD1cPFppTvmpjLNHRfwP9zeP4nBOHHgOv7grzmvCs6QY=
