version: 1.4.{build}

skip_non_tags: true

image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

environment:
  GH_TOKEN:
    secure: 2+1HLAk/YGWqOMnjgsx5nII2huvHAlPkO24vJBqggRmcyy9FhiekaaMDTsRiRnRX

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  # - choco upgrade yarn --ignore-dependencies
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  #- yarn test
  # - yarn build
  - yarn run release:predraft

test: off
