version: 1.4.{build}

# skip_non_tags: true

image: Visual Studio 2017

platform:
  - x64

#cache:
#  - node_modules
#  - '%APPDATA%\npm-cache'
#  - '%USERPROFILE%\.electron'
#  - '%USERPROFILE%\AppData\Local\Yarn\cache'

environment:
  GH_TOKEN:
    secure: 2+1HLAk/YGWqOMnjgsx5nII2huvHAlPkO24vJBqggRmcyy9FhiekaaMDTsRiRnRX
  COVERALLS_REPO_TOKEN:
    secure: 5CQKw1+Is8KphKjmT2emU/C7eNlZN3OEteemQZjOjJl47BVABYr1SOZ+IX82NSWy

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - choco upgrade yarn
  - git reset --hard HEAD
  - yarn
  - node --version
  - yarn autoclean
  - yarn run clean
  - yarn run lint
configuration: Debug

for:
-
  test: off
  build_script:
    - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { yarn run release:predraft }
  configuration: Release
  deploy:
    provider: Environment
    name: production
    on:
      appveyor_repo_tag: true
-
  branches:
    only:
      - ci
  test_script:
    - git config --global user.email "appveyor@appveyor.com"
    - git config --global user.name "AppVeyorBot"
    - ps: $(git stash | Out-Host; $?) -or $(exit 1 | Out-Host; $?)
    - ps: $(git remote set-branches --add origin develop | Out-Host; $?) -or $(exit 1 | Out-Host; $?)
    - git fetch origin develop
    - git checkout --track origin/develop
    - git checkout $env:APPVEYOR_REPO_BRANCH
    - git checkout develop
    - yarn
    - yarn run clean
    - yarn run unit
    - yarn run pack
    - yarn run cucumber:postpack:impl
  after_test:
    - yarn run cucumber:report:badge
  on_success:
    - ps: $(git add --all . | Out-Host; $?) -or $(exit 1 | Out-Host; $?)
    - git commit -m 'appveyor Updating branch from appveyor build.'
    - git push origin $env:APPVEYOR_REPO_BRANCH
  build: off
  deploy: off
  configuration: Mergeandtest
-
  branches:
    only:
      - testci
      - master
  test_script:
    - yarn run clean
    - yarn run unit
    - yarn run pack
    - yarn run cucumber:postpack:impl
  build: off
  deploy: off
  configuration: Test
